/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
//  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
//

sistema_operacional: {
  "Sistemas Operacionais": [{type:'autogenerated',dirName:'Sistemas Operacionais'}],
},

Redes: {
  "Redes": [{type:'autogenerated',dirName:'Redes'}],
},

Armazenamento: {
  "Storage": [{type:'autogenerated',dirName:'Armazenamento'}],
},

Virtualizacao: {
  "Virtualização": [{type:'autogenerated',dirName:'Virtualização'}],
},

};
module.exports = sidebars;